# Generated by Django 5.0.3 on 2024-03-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='city',
            new_name='area_name',
        ),
    ]
