# Generated by Django 5.0.3 on 2024-03-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_city_hotel_area_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='area_name',
            new_name='area',
        ),
    ]
